# Generated by Django 4.1.7 on 2024-06-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('message', models.TextField(max_length=200)),
            ],
            options={
                'db_table': 'action_table',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'admin_table',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Prefer not to say')], max_length=1)),
                ('dateofbirth', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(default='default_password', max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('contact', models.BigIntegerField(unique=True)),
                ('registrationtime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customer_table',
            },
        ),
        migrations.CreateModel(
            name='Devotional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('message', models.TextField(max_length=200)),
            ],
            options={
                'db_table': 'devotional_table',
            },
        ),
        migrations.CreateModel(
            name='Horror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('message', models.TextField(max_length=200)),
            ],
            options={
                'db_table': 'horror_table',
            },
        ),
        migrations.CreateModel(
            name='Insta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('instaid', models.EmailField(max_length=50, unique=True)),
                ('link', models.TextField(max_length=50)),
            ],
            options={
                'db_table': 'insta_table',
            },
        ),
        migrations.CreateModel(
            name='Newspaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('Pages', models.IntegerField()),
                ('side', models.CharField(choices=[('tl', 'top left'), ('tr', 'top right'), ('bl', 'bottom left'), ('br', 'bottom rigth')], max_length=10)),
                ('content', models.TextField(max_length=200)),
                ('image', models.FileField(upload_to='newsimages')),
            ],
            options={
                'db_table': 'newspaper_table',
            },
        ),
        migrations.CreateModel(
            name='Pomplet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('Pagecount', models.IntegerField()),
                ('fold', models.CharField(choices=[('H', 'horizontal'), ('V', 'vertical')], max_length=10)),
                ('content', models.TextField(max_length=200)),
                ('image', models.FileField(upload_to='pompletimages')),
            ],
            options={
                'db_table': 'pomplet_table',
            },
        ),
    ]
